apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    ## set the path to the folder where the Helm chart is stored
    path: project/helm
    ## set the base repo
    repoURL: https://github.com/rednotion/udacity_nd064
    targetRevision: HEAD
  syncPolicy: {}