apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: app
        image: rednotion/udacity_nd064_techtrends:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 3111
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 3111
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 3111