name: "TechTrends - Package with Docker"
# triggers for action to run
on:
  push:
    branches: [ main ]

# workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        # with:
        #   context: ./project/techtrends
        #   file: ./Dockerfile
        #   platforms: linux/amd64, linus/arm64
        #   push: true
        #   tags: {{ YOUR_DOCKERHUB_REPO }}/techtrends:latest